import React from "react";

class ImageCard extends React.Component {
    constructor(props) {
        super(props);

        this.state = { spans: 0 };

        //Get a handle on some element generated by a tag. Equivalent to DOM.
        //here to get the height of the image through React instead of VanillaJS
        this.imageRef = React.createRef();
    }

    componentDidMount() {
        //In the browser it will display the data, but in reality it is null as the image hasn't loaded yet
        console.log(this.imageRef);
        //When the image is loaded, we can access the value with an event
        this.imageRef.current.addEventListener("load", this.setSpans);
    }

    setSpans = () => {
        const height = this.imageRef.current.clientHeight;

        /* see ImageList.css
        .image-list {
            [...]
            grid-auto-rows: 10px;
        }
        */
        const spans = Math.ceil(height / 10);
        this.setState({ spans: spans });
    };

    render() {
        const { description, urls } = this.props.image;
        const { spans } = this.state;

        return (
            <div style={{ gridRowEnd: `span ${spans}` }}>
                <img ref={this.imageRef} alt={description} src={urls.regular} />
            </div>
        );
    }
}

export default ImageCard;
